apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: gracefulapp
  name: gracefulapp
  namespace: default
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 0
  selector:
    matchLabels:
      app: gracefulapp
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gracefulapp
        version: "1.18"
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: gracefulapp112312:latest
        name: gracefulapp
        resources: {}
        imagePullPolicy: Never
status: {}
